click("Windows.png")
sleep(1)
type("cmd\n")
sleep(1)
type("notepad\n")
sleep(1)
click("File.png")
click("Open....png")
wait("FileTest.png")
click("FileTest.png")
click("Open.png")
type("a", KeyModifier.CTRL)
type("World")
click("File.png")
click("SaveAs.png")
type("NewName")
click(Location(866, 670))
